# Generated by Django 4.1.7 on 2023-03-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_year_in_school_blog_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='posted_at',
        ),
    ]
