# Generated by Django 4.1.7 on 2023-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_author_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
