# Generated by Django 4.1.7 on 2023-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
