# Generated by Django 4.1.7 on 2023-03-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='student_id',
        ),
    ]
