# Generated by Django 4.1.7 on 2023-03-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blog_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='StudentID',
            field=models.CharField(default='', max_length=8),
        ),
    ]
