# Generated by Django 4.1.7 on 2023-03-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='StudentID',
            field=models.CharField(default='', help_text='학번을 입력해주세요(예시:20181020)', max_length=8),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='블로그 제목을 작성해주세요', max_length=100),
        ),
    ]
